# Training hyperparameters

# Optimizer settings
lr: 3.0e-4
weight_decay: 0.01

# Training settings
epochs: 100
batch_size: 128  # Per GPU batch size
num_workers: 4

# AMP (Automatic Mixed Precision)
use_amp: true

# Checkpointing
checkpoint_every: 10  # Save checkpoint every N epochs

# Resume options
resume_from: null  # (Legacy) Path to specific checkpoint file
resume_run_dir: null  # Path to run directory (e.g., "output/runs/my_run"). When set, config from that run will be loaded and used.
resume_epoch: null  # Specific epoch to resume from, or null for best_model

